/* huangying */
#ifndef IRM_ERROR_H
#define IRM_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

extern __thread int irm_errno;

enum {
    IRM_OK = 0,
    IRM_MEMORY_POOL_CREATE_MMAP = 1,
    IRM_MEMORY_SLICE_CREATE_MMAP = 2,
    IRM_ERR_EFVI_NETIO_CREATE_CALLOC = 3,
    IRM_ERR_EFVI_DRIVER_OPEN = 4,
    IRM_ERR_ALLOC_EFVI = 5, 
    IRM_ERR_EFCTX_INIT_SET_IP4_LOCAL = 6,
    IRM_ERR_EFCTX_INIT_FILTER_ADD = 7,
    IRM_ERR_EFVI_PD_ALLOC = 9,
    IRM_ERR_EFVI_MEMREG_ALLOC = 10,

    IRM_ERR_SEND_AGAIN = 11,

    IRM_ERR_NATIVE_NETIO_CREATE_CALLOC = 12,
    IRM_ERR_NATIVE_NETIO_INGRESS_RECV_MBUF = 13,
    IRM_ERR_NATIVE_NETIO_INGRESS_AGAIN = 14,
    IRM_ERR_NATIVE_NETIO_INGRESS_RECVFROM = 15,
    IRM_ERR_NATIVE_NETIO_EGRESS_RECV_MBUF = 16,
    IRM_ERR_NATIVE_NETIO_EGRESS_RECVFROM = 17,
    IRM_ERR_NATIVE_NETIO_EGRESS_AGAIN = 18,
    IRM_ERR_NATIVE_NETIO_SENDTO = 19,
    IRM_ERR_NATIVE_CREATE_LOCAL_SOCKET = 20,
    IRM_ERR_NATIVE_CREATE_LOCAL_BIND = 21,
    IRM_ERR_NATIVE_CREATE_LOCAL_MC_TTL = 22,
    IRM_ERR_NATIVE_CREATE_LOCAL_MC_LOOP = 23,
    IRM_ERR_NATIVE_CREATE_LOCAL_TOS = 24,

    IRM_ERR_NETIO_ADD_MCGROUP_SOCKET = 25,
    IRM_ERR_NETIO_ADD_MCGROUP_SETSOCKOPT = 26,
    IRM_ERR_NETIO_ADD_MCGROUP_BIND = 27,
    IRM_ERR_NETIO_ADD_MCGROUP_ADD_MEMBERSHIP = 28,

    IRM_ERR_HANDLE = 29,

    IRM_ERR_CONFIG_LOCAL_IP = 30,
    IRM_ERR_CONFIG_ADDR = 31,
    IRM_ERR_CONFIG_IO_MODE = 32,
    IRM_ERR_CONFIG = 33,
    IRM_ERR_CONFIG_HUGEPAGE = 34,

    IRM_ERR_SUB_CONTEXT_CALLOC = 35,
    IRM_ERR_SUB_CONTEXT_EVENT_LOOP = 36,
    IRM_ERR_SUB_CONTEXT_PUB_INFO_MMAP = 37,

    IRM_ERR_MSG = 38,
    IRM_ERR_HUGEPAGE_ENV = 39,
    IRM_ERR_MKSTEMP = 40,
    IRM_ERR_FSTATFS = 41,
    IRM_ERR_FTRUNCATE = 42,
    IRM_ERR_SET_CORE = 43,
    IRM_ERR_SET_THREAD_NAME = 44,
    IRM_ERR_SET_FIFO = 45,
    IRM_ERR_RING_SET_MAX_SOCKET = 46,
    IRM_ERR_ETHTOOL_GET_RING_IOCTL = 47,
    IRM_ERR_ETHTOOL_SET_RING_IOCTL = 48,
    IRM_ERR_LOAD_STATE_OPEN = 49,
    IRM_ERR_LOAD_STATE_MMAP = 50,
    IRM_ERR_MKDIR_PATH = 51,
    IRM_ERR_SYS_MKDIR = 52,
    IRM_ERR_MAKE_PATH = 53,
    IRM_ERR_PATH_EXISTED = 54, 
    IRM_ERR_MAKE_PATH_NAME = 55,
    IRM_ERR_MAKE_PATH_STAT = 56,
    IRM_ERR_FORMAT_FTRUNCATE = 57,
    IRM_ERR_FORMAT_FTRUNCATE_SIZE = 58,
    IRM_ERR_LOAD_VERSION_PREAD = 59,
    IRM_ERR_LOAD_META = 60,
    IRM_ERR_LOAD_META_SIZE = 61,
    IRM_ERR_LOAD_VERSION = 62,
    IRM_ERR_FILE_READY_FSTAT = 63,
    

    IRM_ERR_PUB_CONTEXT_CALLOC = 64,
    IRM_ERR_PUB_CONTEXT_EVENT_LOOP = 65,
    IRM_ERR_PUB_CONTEXT_SUB_INFO_MMAP = 66,
    IRM_ERR_PUB_INVITATION = 67,

    IRM_ERR_IFNAME_IP_GETIFADDRS = 68, 
    IRM_ERR_IFNAME_IP_MATCH = 69,

    IRM_ERR_PUT_AGAIN = 70,
    IRM_ERR_GET_AGAIN = 71,
    IRM_ERR_CLOSE_DATA = 72,

    IRM_HASHTABLE_REMOVE_ERROR = 73,

    IRM_ERR_PUSH_AGAIN = 75,
    
    IRM_ERR_RUNTIME_OPEN_FAILED = 77,
    IRM_ERR_RUNTIME_FSTATFS = 78,
    IRM_ERR_RUNTIME_FTRUNCATE = 79, 
    IRM_ERR_RUNTIME_MMAP = 80, 

    IRM_ERR_SET_RCVBUF = 81,
    IRM_ERR_SET_SNDBUF = 82,

    IRM_ERR_RING_INIT = 83,
    IRM_ERR_RING_ENQUEUE_NOBUFS = 84,
    IRM_ERR_RING_DEQUEUE_NOENTRY = 85,

    IRM_ERR_NETIO_SET_OPTION = 86,

    IRM_ERR_MAX
};

#ifdef __cplusplus
}
#endif

#endif
